spring.application.name=api-gateway
server.port=8030

# JWT
jwt.public.key=classpath:public_key.pem

# Actuator
management.endpoints.web.exposure.include=prometheus,health,info

logging.level.org.springframework.security=DEBUG

# Logging
logging.level.org.springframework.web=INFO
logging.level.com.yourorg.gateway=DEBUG